cc_library(
    name = "v8_platform_initializer",
    srcs = ["v8_platform_initializer.cc"],
    hdrs = ["v8_platform_initializer.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_absl//absl/base",
        "@v8",
    ],
)
